services:
  backend:
    build:
      context: backend
      target: prod # dev, prod
    container_name: backend
    ports:
      - "8000:443"
    volumes:
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private

  frontend:
    build:
      context: frontend
      target: prod # dev, prod
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private